[package]
name = "e2rustcli"
description = "A template for CLI tools written in Rust."
version = "0.0.1"
authors = ["evnp <ep@e2.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
